# Generated by Django 4.1.2 on 2022-10-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinfo',
            name='avatar',
            field=models.ImageField(default='avatar.jpg', upload_to='dp'),
        ),
    ]
