# Generated by Django 4.1.2 on 2022-10-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_appinfo_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appinfo',
            name='avatar',
            field=models.ImageField(upload_to='dp'),
        ),
    ]
